on: [push]

name: build and push

jobs:
  build_and_push:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: philips-software/docker-ci-scripts@v2.0.1
      with:
        dockerfile: ./
        image-name: terraform-provider-hsdp
        tags: latest 0.4.0
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware 
        GITHUB_ORGANIZATION: philips-software
