name: Terraform Provider Tests

on:
  push:
    branches: [main]
    paths:
      - '**.go'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [main]
    paths:
      - '**.go'

permissions:
  # Permission for checking out code
  contents: read

jobs:
  acceptance:
    name: Acceptance Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.*'
          terraform_wrapper: false
      - run: go test -v -cover ./...
        env:
          TF_ACC: '1'
          HSDP_REGION: ${{ secrets.HSDP_REGION }}
          HSDP_ENVIRONMENT: ${{ secrets.HSDP_ENVIRONMENT }}
          HSDP_IAM_ACC_ORG_GUID: ${{ secrets.HSDP_IAM_ACC_ORG_GUID }}
          HSDP_IAM_ACC_USER_GUID: ${{ secrets.HSDP_IAM_ACC_USER_GUID }}
          HSDP_IAM_SERVICE_ID: ${{ secrets.HSDP_IAM_SERVICE_ID }}
          HSDP_IAM_SERVICE_PRIVATE_KEY: ${{ secrets.HSDP_IAM_SERVICE_PRIVATE_KEY }}
          HSDP_IAM_OAUTH2_CLIENT_ID: ${{ secrets.HSDP_IAM_OAUTH2_CLIENT_ID }}
          HSDP_IAM_OAUTH2_PASSWORD: ${{ secrets.HSDP_IAM_OAUTH2_PASSWORD }}
          HSDP_UAA_USERNAME: ${{ secrets.HSDP_UAA_USERNAME }}
          HSDP_UAA_PASSWORD: ${{ secrets.HSDP_UAA_PASSWORD }}
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - run: go test -v -cover ./...
